[package]
name = "workbench-niri"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
niri-ipc.workspace = true
serde_json.workspace = true
shellexpand.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
workbench-core = { path = "../workbench-core" }
