[package]
name = "niri-workbench-ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Native GTK interface for niri-workbench"

[dependencies]
anyhow.workspace = true
gtk4.workspace = true
libadwaita.workspace = true
niri-ipc.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
tokio.workspace = true
toml.workspace = true
workbench-core = { path = "../workbench-core" }
workbench-niri = { path = "../workbench-niri" }
